<?xml version="1.0" encoding="utf-8"?><Database Name="Placeberry_dev" Class="dbPlaceberryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.5.89;Initial Catalog=Placeberry_dev;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Placeberry_CS" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UnwantedWord" Member="UnwantedWords">
    <Type Name="UnwantedWord">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Source_UnwantedWord" Member="Source" ThisKey="SourceId" OtherKey="Id" Type="Source" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdvertRaw" Member="AdvertRaws">
    <Type Name="AdvertRaw">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenerationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HashCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SystemStatus" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GroupType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GroupSubType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SourceCategory" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccommSubType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="VacationType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AdvertCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UrlLink" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="Stars" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocationDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Subregion" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PriceOld" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PriceFrom" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PriceDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Date1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Date2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DaysNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Beach" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BeachDistanceM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DistanceFromCentreM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PetsDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="InfoDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Generation_AdvertRaw" Member="Generation" ThisKey="GenerationId" OtherKey="Id" Type="Generation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdvertUltimateTable" Member="AdvertUltimateTables">
    <Type Name="AdvertUltimateTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdvertId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UltimateTableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MatchCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatchPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UltimateTable_AdvertUltimateTable" Member="UltimateTable" ThisKey="UltimateTableId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="Advert_AdvertUltimateTable" Member="Advert" ThisKey="AdvertId" OtherKey="Id" Type="Advert" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CandidateWord" Member="CandidateWords">
    <Type Name="CandidateWord">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="QueryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertRawId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ObjectTypeCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Language_CandidateWord" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbrevation" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="Currency_CurrencyRelation" Member="CurrencyRelations" ThisKey="Id" OtherKey="CurrencyId" Type="CurrencyRelation" />
      <Association Name="Currency_CurrencyRelation1" Member="CurrencyRelations1" ThisKey="Id" OtherKey="CurrencyId_2" Type="CurrencyRelation" />
      <Association Name="Currency_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="CurrencyId" Type="UltimateTable" />
      <Association Name="Currency_Advert" Member="Adverts" ThisKey="Id" OtherKey="CurrencyId" Type="Advert" />
    </Type>
  </Table>
  <Table Name="dbo.CurrencyRelation" Member="CurrencyRelations">
    <Type Name="CurrencyRelation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(15,4) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="Currency_CurrencyRelation" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="Currency_CurrencyRelation1" Member="Currency1" ThisKey="CurrencyId_2" OtherKey="Id" Type="Currency" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Generation" Member="Generations">
    <Type Name="Generation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Generation_AdvertRaw" Member="AdvertRaws" ThisKey="Id" OtherKey="GenerationId" Type="AdvertRaw" />
    </Type>
  </Table>
  <Table Name="dbo.Language" Member="Languages">
    <Type Name="Language">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbrevation" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Language_CandidateWord" Member="CandidateWords" ThisKey="Id" OtherKey="LanguageId" Type="CandidateWord" />
      <Association Name="Language_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="LanguageId" Type="UltimateTable" />
    </Type>
  </Table>
  <Table Name="dbo.QueryWeb" Member="QueryWebs">
    <Type Name="QueryWeb">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Query" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Source" Member="Sources">
    <Type Name="Source">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Source_UnwantedWord" Member="UnwantedWords" ThisKey="Id" OtherKey="SourceId" Type="UnwantedWord" />
      <Association Name="Source_Advert" Member="Adverts" ThisKey="Id" OtherKey="SourceId" Type="Advert" />
    </Type>
  </Table>
  <Table Name="dbo.tblAdvertEN" Member="tblAdvertENs">
    <Type Name="tblAdvertEN">
      <Column Name="AdvertID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdvertCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccommSubType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Stars" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VacationType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="URLLink" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SourceCategory" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PriceFromPersonDayEUR" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="PriceOldPersonDayEUR" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="NumDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Beach" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BeachDistanceM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistanceFromCenterM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subregion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PetsAllowed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PetsSpec" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTable" Member="UltimateTables">
    <Type Name="UltimateTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="RegexExpression" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="RegexExpressionExtended" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjectTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsIgnored" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapturingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapturingOperator" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UltimateTable_AdvertUltimateTable" Member="AdvertUltimateTables" ThisKey="Id" OtherKey="UltimateTableId" Type="AdvertUltimateTable" />
      <Association Name="UltimateTable_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="ParentId" Type="UltimateTable" />
      <Association Name="UltimateTable_UltimateTableRelation" Member="UltimateTableRelations" ThisKey="Id" OtherKey="ParentId" Type="UltimateTableRelation" />
      <Association Name="UltimateTable_UltimateTableRelation1" Member="UltimateTableRelations1" ThisKey="Id" OtherKey="ChildId" Type="UltimateTableRelation" />
      <Association Name="Currency_UltimateTable" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="Language_UltimateTable" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="UltimateTable_UltimateTable" Member="UltimateTable1" ThisKey="ParentId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTableObjectType_UltimateTable" Member="UltimateTableObjectType" ThisKey="ObjectTypeId" OtherKey="Id" Type="UltimateTableObjectType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableObjectType" Member="UltimateTableObjectTypes">
    <Type Name="UltimateTableObjectType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UltimateTableObjectType_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="ObjectTypeId" Type="UltimateTable" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableRelation" Member="UltimateTableRelations">
    <Type Name="UltimateTableRelation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UltimateTable_UltimateTableRelation" Member="UltimateTable" ThisKey="ParentId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTable_UltimateTableRelation1" Member="UltimateTable1" ThisKey="ChildId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advert" Member="Adverts">
    <Type Name="Advert">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccommodationType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="LocationDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceOld" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceDesc" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="HashCode" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateTo" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PetsDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdvertRawId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatchedWordsCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAdvertCreated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateUrlChecked" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="BadUrlCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccommodationAdvert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Advert_AdvertUltimateTable" Member="AdvertUltimateTables" ThisKey="Id" OtherKey="AdvertId" Type="AdvertUltimateTable" />
      <Association Name="Currency_Advert" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="Source_Advert" Member="Source" ThisKey="SourceId" OtherKey="Id" Type="Source" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetAdvert" Method="GetAdvert">
    <Parameter Name="AdvertID" Parameter="advertID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAdvertResult">
      <Column Name="AdvertID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccommSubType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VacationType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Stars" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Beach" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subregion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PetsSpec" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="URLLink" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PriceFromPersonDayEUR" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="PriceOldPersonDayEUR" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
      <Column Name="PriceChngPerc" Type="System.Decimal" DbType="Decimal(0,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TestConvert" Method="TestConvert">
    <ElementType Name="TestConvertResult">
      <Column Name="NewTestDateTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProcessAdvertRow" Method="ProcessAdvertRow">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.QueryParsing" Method="QueryParsing">
    <Parameter Name="query" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.QueryParsingUltimate" Method="QueryParsingUltimate">
    <Parameter Name="query" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SearchTemp" Method="SearchTemp">
    <Parameter Name="query" Type="System.String" DbType="NVarChar(2000)" />
    <ElementType Name="SearchTempResult">
      <Column Name="AdvertID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AccommSubType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VacationType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Beach" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subregion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PetsSpec" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetResults" Method="GetResults" IsComposable="true">
    <Parameter Name="query" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <Parameter Name="top" Type="System.Int32" DbType="Int" />
    <Return Type="object" />
  </Function>
</Database>