<?xml version="1.0" encoding="utf-8"?><Database Name="Placeberry_dev" Class="UltimateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.5.89;Initial Catalog=Placeberry_dev;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Placeberry_CS" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Language" Member="Languages">
    <Type Name="Language">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbrevation" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Association Name="Language_AccommodationDescription" Member="AccommodationDescriptions" ThisKey="Id" OtherKey="LanguageId" Type="AccommodationDescription" />
      <Association Name="Language_UltimateTableTranslation" Member="UltimateTableTranslations" ThisKey="Id" OtherKey="LanguageId" Type="UltimateTableTranslation" />
      <Association Name="Language_PopularQuery" Member="PopularQueries" ThisKey="Id" OtherKey="LanguageId" Type="PopularQuery" />
      <Association Name="Language_RegexLanguageRule" Member="RegexLanguageRules" ThisKey="Id" OtherKey="LanguageId" Type="RegexLanguageRule" />
      <Association Name="Language_AgencyDescription" Member="AgencyDescriptions" ThisKey="Id" OtherKey="LanguageId" Type="AgencyDescription" />
      <Association Name="Language_Agency" Member="Agencies" ThisKey="Id" OtherKey="LangaugeId" Type="Agency" />
      <Association Name="Language_UltimateTableUrlTag" Member="UltimateTableUrlTags" ThisKey="Id" OtherKey="LanguageId" Type="UltimateTableUrlTag" />
      <Association Name="Language_AccommodationUrlTag" Member="AccommodationUrlTags" ThisKey="Id" OtherKey="LanguageId" Type="AccommodationUrlTag" />
    </Type>
  </Table>
  <Table Name="dbo.Image" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Src" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Alt" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2500)" CanBeNull="true" />
      <Association Name="Image_AccommodationImage" Member="AccommodationImages" ThisKey="Id" OtherKey="ImageId" Type="AccommodationImage" />
      <Association Name="Image_Agency" Member="Agencies" ThisKey="Id" OtherKey="LogoId" Type="Agency" />
    </Type>
  </Table>
  <Table Name="dbo.AccommodationImages" Member="AccommodationImages">
    <Type Name="AccommodationImage">
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Image_AccommodationImage" Member="Image" ThisKey="ImageId" OtherKey="Id" Type="Image" IsForeignKey="true" />
      <Association Name="Accommodation_AccommodationImage" Member="Accommodation" ThisKey="AccommodationId" OtherKey="Id" Type="Accommodation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbrevation" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="Currency_AccommodationPrice" Member="AccommodationPrices" ThisKey="Id" OtherKey="CurrencyId" Type="AccommodationPrice" />
      <Association Name="Currency_Advert" Member="Adverts" ThisKey="Id" OtherKey="CurrencyId" Type="Advert" />
    </Type>
  </Table>
  <Table Name="dbo.AccommodationCity" Member="AccommodationCities">
    <Type Name="AccommodationCity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Subregion" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PendingApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UltimateTableId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="AccommodationCity_Accommodation" Member="Accommodations" ThisKey="Id" OtherKey="AccommodationCityId" Type="Accommodation" />
      <Association Name="UltimateTable_AccommodationCity" Member="UltimateTable" ThisKey="UltimateTableId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccommodationDescription" Member="AccommodationDescriptions">
    <Type Name="AccommodationDescription">
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Language_AccommodationDescription" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="Accommodation_AccommodationDescription" Member="Accommodation" ThisKey="AccommodationId" OtherKey="Id" Type="Accommodation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccommodationPrice" Member="AccommodationPrices">
    <Type Name="AccommodationPrice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Currency_AccommodationPrice" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="Accommodation_AccommodationPrice" Member="Accommodation" ThisKey="AccommodationId" OtherKey="Id" Type="Accommodation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlaceberryUser" Member="PlaceberryUsers">
    <Type Name="PlaceberryUser">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ActivationKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ResetPasswordKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="PlaceberryUser_Agency" Member="Agencies" ThisKey="UserId" OtherKey="ManagerId" Type="Agency" />
      <Association Name="aspnet_User_PlaceberryUser" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_PlaceberryUser" Member="PlaceberryUser" ThisKey="UserId" OtherKey="UserId" Type="PlaceberryUser" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableRelation" Member="UltimateTableRelations">
    <Type Name="UltimateTableRelation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChildId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UltimateTable_UltimateTableRelation" Member="Parent" ThisKey="ParentId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTable_UltimateTableRelation1" Member="Child" ThisKey="ChildId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableTranslation" Member="UltimateTableTranslations">
    <Type Name="UltimateTableTranslation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UltimateTableId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Regex" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IgnoreRegex" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Association Name="Language_UltimateTableTranslation" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="UltimateTable_UltimateTableTranslation" Member="UltimateTable" ThisKey="UltimateTableId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PopularQueries" Member="PopularQueries">
    <Type Name="PopularQuery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Query" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Language_PopularQuery" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableObjectType" Member="UltimateTableObjectTypes">
    <Type Name="UltimateTableObjectType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="UltimateTableObjectType_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="ObjectTypeId" Type="UltimateTable" />
    </Type>
  </Table>
  <Table Name="dbo.RegexLanguageRules" Member="RegexLanguageRules">
    <Type Name="RegexLanguageRule">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="RegexExpression" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ReplaceWith" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ignore" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Language_RegexLanguageRule" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AgencyDescription" Member="AgencyDescriptions">
    <Type Name="AgencyDescription">
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Language_AgencyDescription" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="Agency_AgencyDescription" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Advert" Member="Adverts">
    <Type Name="Advert">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccommodationType" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ContactInfo" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="LocationDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceTo" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceOld" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceDesc" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="HashCode" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateTo" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateDesc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PetsDesc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdvertRawId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatchedWordsCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAdvertCreated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateUrlChecked" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="BadUrlCnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PlaceberryAdvert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CapacityMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccommodationTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertInfoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgencyName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Currency_Advert" Member="Currency" ThisKey="CurrencyId" OtherKey="Id" Type="Currency" IsForeignKey="true" />
      <Association Name="UltimateTable_Advert" Member="UltimateTable" ThisKey="AccommodationTypeId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTable_Advert1" Member="AdvertInfo" ThisKey="AdvertInfoId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="Agency_Advert" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" />
      <Association Name="Accommodation_Advert" Member="Accommodation" ThisKey="AccommodationId" OtherKey="Id" Type="Accommodation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.CarrierLine" Member="CarrierLines">
    <Type Name="CarrierLine">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CarrierLine_CarrierLineSeason" Member="CarrierLineSeasons" ThisKey="Id" OtherKey="CarrierLineId" Type="CarrierLineSeason" />
      <Association Name="Agency_CarrierLine" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.CarrierLineSeason" Member="CarrierLineSeasons">
    <Type Name="CarrierLineSeason">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CarrierLineId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CarrierLineSeason_CarrierLineTimeTable" Member="CarrierLineTimeTables" ThisKey="Id" OtherKey="CarrierLineSeasonId" Type="CarrierLineTimeTable" />
      <Association Name="CarrierLine_CarrierLineSeason" Member="CarrierLine" ThisKey="CarrierLineId" OtherKey="Id" Type="CarrierLine" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CarrierLineTimeTable" Member="CarrierLineTimeTables">
    <Type Name="CarrierLineTimeTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CarrierLineSeasonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlaceFrom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PlaceTo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PlaceFromId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PlaceToId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeDeparture" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="TimeArrival" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="TimeFixedMinutes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaysAll" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayMonday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayTuesday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayWednesday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayThursday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DayFriday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaySaturday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaySunday" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CarrierLineSeason_CarrierLineTimeTable" Member="CarrierLineSeason" ThisKey="CarrierLineSeasonId" OtherKey="Id" Type="CarrierLineSeason" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UltimateTable_CarrierLineTimeTable" Member="UltimateTable" ThisKey="PlaceFromId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTable_CarrierLineTimeTable1" Member="UltimateTable1" ThisKey="PlaceToId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTable" Member="UltimateTables">
    <Type Name="UltimateTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="RegexExpression" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="RegexExpressionExtended" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IgnoreRegex" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="ObjectTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsIgnored" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapturingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapturingOperator" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Accuweather" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Association Name="UltimateTable_AccommodationCity" Member="AccommodationCities" ThisKey="Id" OtherKey="UltimateTableId" Type="AccommodationCity" />
      <Association Name="UltimateTable_UltimateTableRelation" Member="UltimateTableRelations" ThisKey="Id" OtherKey="ParentId" Type="UltimateTableRelation" />
      <Association Name="UltimateTable_UltimateTableRelation1" Member="UltimateTableRelations1" ThisKey="Id" OtherKey="ChildId" Type="UltimateTableRelation" />
      <Association Name="UltimateTable_UltimateTableTranslation" Member="UltimateTableTranslations" ThisKey="Id" OtherKey="UltimateTableId" Type="UltimateTableTranslation" />
      <Association Name="UltimateTable_Advert" Member="Adverts" ThisKey="Id" OtherKey="AccommodationTypeId" Type="Advert" />
      <Association Name="UltimateTable_Advert1" Member="Adverts1" ThisKey="Id" OtherKey="AdvertInfoId" Type="Advert" />
      <Association Name="UltimateTable_CarrierLineTimeTable" Member="CarrierLineTimeTables" ThisKey="Id" OtherKey="PlaceFromId" Type="CarrierLineTimeTable" />
      <Association Name="UltimateTable_CarrierLineTimeTable1" Member="CarrierLineTimeTables1" ThisKey="Id" OtherKey="PlaceToId" Type="CarrierLineTimeTable" />
      <Association Name="UltimateTable_UltimateTable" Member="UltimateTables" ThisKey="Id" OtherKey="ParentId" Type="UltimateTable" />
      <Association Name="UltimateTable_UltimateTableInfo" Member="UltimateTableInfos" ThisKey="Id" OtherKey="UltimateTableId" Type="UltimateTableInfo" />
      <Association Name="UltimateTable_UltimateTableUrlTag" Member="UltimateTableUrlTags" ThisKey="Id" OtherKey="UltimateTableId" Type="UltimateTableUrlTag" />
      <Association Name="UltimateTable_Accommodation" Member="Accommodations" ThisKey="Id" OtherKey="TypeId" Type="Accommodation" />
      <Association Name="UltimateTable_UltimateTable" Member="UltimateTable1" ThisKey="ParentId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
      <Association Name="UltimateTableObjectType_UltimateTable" Member="UltimateTableObjectType" ThisKey="ObjectTypeId" OtherKey="Id" Type="UltimateTableObjectType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableInfo" Member="UltimateTableInfos">
    <Type Name="UltimateTableInfo">
      <Column Name="UltimateTableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WikiLink" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="WikiDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueryMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="UltimateTable_UltimateTableInfo" Member="UltimateTable" ThisKey="UltimateTableId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Agency" Member="Agencies">
    <Type Name="Agency">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhone" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContactEmail" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LogoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlWebsite" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ManagerId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Private" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LangaugeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Agency_AgencyDescription" Member="AgencyDescriptions" ThisKey="Id" OtherKey="AgencyId" Type="AgencyDescription" />
      <Association Name="Agency_Advert" Member="Adverts" ThisKey="Id" OtherKey="AgencyId" Type="Advert" />
      <Association Name="Agency_CarrierLine" Member="CarrierLines" ThisKey="Id" OtherKey="AgencyId" Type="CarrierLine" />
      <Association Name="Agency_AgencyUrlTag" Member="AgencyUrlTags" ThisKey="Id" OtherKey="AgencyId" Type="AgencyUrlTag" />
      <Association Name="Agency_AccommodationUrlTag" Member="AccommodationUrlTags" ThisKey="Id" OtherKey="AgencyId" Type="AccommodationUrlTag" />
      <Association Name="Agency_Accommodation" Member="Accommodations" ThisKey="Id" OtherKey="AgencyId" Type="Accommodation" />
      <Association Name="Language_Agency" Member="Language" ThisKey="LangaugeId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="PlaceberryUser_Agency" Member="PlaceberryUser" ThisKey="ManagerId" OtherKey="UserId" Type="PlaceberryUser" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Image_Agency" Member="Image" ThisKey="LogoId" OtherKey="Id" Type="Image" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_FormatedAdvertListing" Member="vw_FormatedAdvertListings">
    <Type Name="vw_FormatedAdvertListing">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PlaceberryAdvert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgencyName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertInfoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NeedsTranslation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceOld" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertRawId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceTitle" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SourceUrl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PriceBaseCurrency" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="DateAdvertCreated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UltimateTableUrlTag" Member="UltimateTableUrlTags">
    <Type Name="UltimateTableUrlTag">
      <Column Name="UltimateTableId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UrlTag" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Language_UltimateTableUrlTag" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="UltimateTable_UltimateTableUrlTag" Member="UltimateTable" ThisKey="UltimateTableId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AgencyUrlTag" Member="AgencyUrlTags">
    <Type Name="AgencyUrlTag">
      <Column Name="UrlTag" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Agency_AgencyUrlTag" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccommodationUrlTag" Member="AccommodationUrlTags">
    <Type Name="AccommodationUrlTag">
      <Column Name="UrlTag" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Agency_AccommodationUrlTag" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" />
      <Association Name="Language_AccommodationUrlTag" Member="Language" ThisKey="LanguageId" OtherKey="Id" Type="Language" IsForeignKey="true" />
      <Association Name="Accommodation_AccommodationUrlTag" Member="Accommodation" ThisKey="AccommodationId" OtherKey="Id" Type="Accommodation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accommodation" Member="Accommodations">
    <Type Name="Accommodation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccommodationCityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CapacityMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pets" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPublished" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PetsSpec" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Activities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Facilities" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsDirty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Association Name="Accommodation_AccommodationImage" Member="AccommodationImages" ThisKey="Id" OtherKey="AccommodationId" Type="AccommodationImage" />
      <Association Name="Accommodation_AccommodationDescription" Member="AccommodationDescriptions" ThisKey="Id" OtherKey="AccommodationId" Type="AccommodationDescription" />
      <Association Name="Accommodation_AccommodationPrice" Member="AccommodationPrices" ThisKey="Id" OtherKey="AccommodationId" Type="AccommodationPrice" />
      <Association Name="Accommodation_Advert" Member="Adverts" ThisKey="Id" OtherKey="AccommodationId" Type="Advert" />
      <Association Name="Accommodation_AccommodationUrlTag" Member="AccommodationUrlTags" ThisKey="Id" OtherKey="AccommodationId" Type="AccommodationUrlTag" />
      <Association Name="AccommodationCity_Accommodation" Member="AccommodationCity" ThisKey="AccommodationCityId" OtherKey="Id" Type="AccommodationCity" IsForeignKey="true" />
      <Association Name="Agency_Accommodation" Member="Agency" ThisKey="AgencyId" OtherKey="Id" Type="Agency" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UltimateTable_Accommodation" Member="UltimateTable" ThisKey="TypeId" OtherKey="Id" Type="UltimateTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetCountryFromIP" Method="GetCountryFromIP">
    <Parameter Name="IP" Parameter="iP" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="country" Type="System.String" DbType="NVarChar(2)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAutoRegex" Method="GetAutoRegex">
    <Parameter Name="term" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <Parameter Name="regex" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetParentCities" Method="GetParentCities">
    <Parameter Name="countryId" Type="System.Int32" DbType="Int" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentCitiesResult">
      <Column Name="Lvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ChildId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParentChildsByType" Method="GetParentChildsByType">
    <Parameter Name="parentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="childTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentChildsByTypeResult">
      <Column Name="Lvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ChildId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAdvert" Method="GetAdvert">
    <Parameter Name="AdvertID" Parameter="advertID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAdvertResult">
      <Column Name="AdvertID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccommodationType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PlaceberryAdvert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccommSubType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VacationType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Stars" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Beach" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Facilities" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Activities" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Region" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Subregion" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Island" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PetsSpec" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="URLLink" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PriceFromPersonDayEUR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceOldPersonDayEUR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceChngPerc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParsedQuery" Method="GetParsedQuery">
    <Parameter Name="query" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParsedQueryResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ObjectTypeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectTypeGroupCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ProcessAccommodationAdvert" Method="ProcessAccommodationAdvert">
    <Parameter Name="AccommodationId" Parameter="accommodationId" Type="System.Int32" DbType="Int" />
    <ElementType Name="ProcessAccommodationAdvertResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetParents" Method="GetParents">
    <Parameter Name="childTitle" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="childId" Type="System.Int32" DbType="Int" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetParentsResult">
      <Column Name="Lvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ObjectTypeCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ObjectTypeGroupCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="UrlTag" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAgencyAdverts" Method="GetAgencyAdverts">
    <Parameter Name="agencyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="languageId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAgencyAdvertsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AccommType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AgencyUrlTag" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AccommodationUrlTag" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PlaceberryAdvert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AgencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgencyName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="AccommodationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertInfoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CapacityMax" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NeedsTranslation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PictureUrl" Type="System.String" DbType="NVarChar(1200)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceOld" Type="System.Decimal" DbType="Decimal(15,2) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Island" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvertRawId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceTitle" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SourceUrl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PriceBaseCurrency" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="DateAdvertCreated" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="AccommDescLangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccommTransLangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>